name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hey Google !"
    - run: ls
    - uses: actions/checkout@v2
    - run: ls
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      env:
        GITHUB_TOKEN: ${{ secrets.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 }}
      run: |
        echo "Connected to GitHub as $(git config --get remote.origin.url)
